export enum Team {

  // From 24_25 season (leave here for test purpose)
  BAYERN_LEVERDUREN = 'BAYERN LEVERDUREN.',
  BEN_FICA = 'BEN FICA',
  BORGO_GRAZZANO = 'BORGO GRAZZANO',
  CCORYO_JUNIORS = 'CCORYO JUNIORS',
  FC_PUSSY_MIX = 'FC PUSSY MIX',
  MANCHESTER_SINTY = 'MANCHESTER SINTY',
  MICCOLILLE = 'MICCOLILLE',
  STARK_INDUSTRIES = 'STARK INDUSTRIES',


  // 25_26 season
  ACK_BOMBA = 'ACK BOMBA',
  AHI_3_CROCIATI = 'AHI 3 CROCIATI',
  ASTON_BIRRA = 'ASTON BIRRA',
  CALCIO_BAILADO = 'CALCIO BAILADO',
  CHIAVOVERONICA = 'CHIAVOVERONICA',
  COCABRODA = 'COCABRODA',
  CSKA_PIAVON = 'CSKA PIAVON',
  DALLAS = 'DALLAS',
  DINAMO_KEYV = 'DINAMO KEYV',
  FC_DIREZIONE = 'FC DIREZIONE',
  GINO_PIPINOTTO = 'GINO PIPIN8',
  GLI_SBORRATI = 'GLI SBORRATI',
  GUNS_N_GOSENS = 'GUNS N GOSENS',
  IL_CANEPARDO = 'IL CANEPARDO',
  IRON_GAS = 'IRON GAS',
  I_RAGAZZI = 'I RAGAZZI',
  JOGA_BENITO = 'JOGA BENITO',
  KANTÉ_CABRIOLET = 'KANTÉ CABRIOLET',
  LOS_ANGELO_UN_ESPERTO = 'LOS ANGELO - UN ESPERTO',
  NAPOLETHANOS = 'NAPOLETHANOS',
  NEROAZZURRI = 'NEROAZZURRI',
  NOT_ATHLETIC_CRODANZO = 'NOT ATHLETIC CRODANZO',
  PARIS_SAN_GENNAR = 'PARIS SAN GENNAR',
  REAL_DUREZZA = 'REAL DUREZZA',
  REAL_GRIFONE = 'REAL GRIFONE',
  REAL_MAKADAM = 'REAL MAKADAM',
  REDBLACK = 'REDBLACK',
  RIVER_BOLUDOS = 'RIVER BOLUDOS',
  SMOKING_BIANCO = 'SMOKING BIANCO.',
  TEAM_DADA = 'TEAM DADA',
  TOTTOMAN = 'TOTTOMAN',
  VILLA_FRIGNAVERA = 'VILLA FRIGNAVERA',
  TBD = 'TBD', // Use it in cup competitions
}

export function getTeamList(): string[] {
  return getEnumValues(Team);
}

// Function to get a list of enum values
function getEnumValues<T extends object>(enumObj: T): string[] {
  return Object.values(enumObj) as string[];
}